### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by c9rl**
identifed > identified

### CODE REVIEW

**Comment by percyhanna** [comment]
@carlbernardo Thanks for this change. Unfortunately, we just launched our new support site yesterday, which is no longer based on this GitHub repo. I'll notify our CS Manager to make sure this fix is applied to the new site (if not already).

@cburns-kissmetrics See above typo fix.

**Comment by cburns-kissmetrics** [comment]
Not able to see any typo fix

_Chris Burns_
Manager of Customer Success | Kissmetrics http://www.kissmetrics.com
(e) cburns@kissmetrics.com

**Comment by percyhanna** [comment]
@cburns-kissmetrics See https://github.com/kissmetrics/km-support/pull/151/files

**Comment by cburns-kissmetrics** [comment]
Updated! Thank you for noticing and letting us know :)

_Chris Burns_
Manager of Customer Success | Kissmetrics http://www.kissmetrics.com
(e) cburns@kissmetrics.com

**Pull request closed without merging**
