### PR TITLE
Update 2012-10-19-ecommerce-essentials.md

### PR DESCRIPTION
**Pull request by andremafei**
You have a draft online ?!

### CODE REVIEW

**Comment by percyhanna** [comment]
@eskfung Can you look at adding some proper documentation to that page?

**Comment by eskfung** [comment]
@andremafei the bulleted list you're modifying demonstrates the format of the actual events below it. I'm not sure your change adds anything meaningful...?

**Comment by andremafei** [comment]
@eskfung you right, now I see it. It was late when I wrote it.

**Comment by eskfung** [comment]
No problem, thanks for keeping an eye out!

**Pull request closed without merging**
