### PR TITLE
Fixing 404 links

### PR DESCRIPTION
**Pull request by ianmain**

### CODE REVIEW

**Comment by ianmain** [comment]
Can you check this out for me?

**Comment by jasoncaldwell** [comment]
Looks good to me, not completely sure about the new sitemap though ... @percyhanna any thoughts?

**Comment by percyhanna** [comment]
Looks good.

**Comment by jasoncaldwell** [comment]
@percyhanna ty!

**Comment by ianmain** [comment]
Thanks @percyhanna. For some reason the sitemap wasn't regenerating locally. Cheers.

**Pull request merged**
