### PR TITLE
Fix: embedded Wistia videos overlap content.

### PR DESCRIPTION
**Pull request by mmlin**
@eskfung Can I do this?

### CODE REVIEW

**Comment by eskfung** [comment]
:+1: :shipit:

**Comment by brittneybrinsfield** [comment]
Can you undo so I can view all my videos origainally

**Comment by eskfung** [comment]
@brittneybrinsfield which support pages are affected?

**Comment by brittneybrinsfield** [comment]
I need you to undo all changes an send back as soon as possible I'll pay u 150$

**Pull request merged**
