### PR TITLE
JavaScript Library Update

### PR DESCRIPTION
**Pull request by dsvedvik**
Reorganized and reformated the JavaScript Library article, removed redundant sections of the article and removed the redundant "Javascript Library Specifics" article (which was a trimmed down version of the JavaScript Library article with no additional information).

### CODE REVIEW

**Comment by dsvedvik** [comment]
Assigning Eric just for the sake of having a second set of eyes look at the PR (been a while, don't want to break the world)

**Comment by eskfung** [comment]
@dsvedvik ooh, `javascript-specific`. As annoying as it is, I'd actually sweep through the whole project for references to `/apis/javascript/javascript-specific/`, because a number of other articles link to that url.

**Comment by eskfung** [comment]
And unfortunately, even though people have made Jekyll plugins for redirects (https://github.com/jekyll/jekyll-redirect-from), Github Pages runs vanilla Jekyll without plugins.

**Comment by dsvedvik** [comment]
Sure, I can just grep it. Thanks.

**Pull request merged**
